language: r

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

sudo: true

fortran: false

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgs-dev
      - qpdf
      - ghostscript
      - librdf0-dev
      - libv8-dev
      - libjq-dev
      - libdb-dev
      - libxml2-dev

r_binary_packages:
  - rmarkdown
  - tinytex
  - knitr
  - xml2
  - hunspell
  - V8

r_github_packages:
  - jimhester/covr

matrix:
  include:
    - r: oldrel
      dist: xenial
      before_install:
        - sudo apt-get update
        - tlmgr install index

    - r: release
      script:
        - R CMD build . --compact-vignettes=gs+qpdf
        - R CMD check *tar.gz --as-cran
      dist: xenial
      before_install:
        - sudo apt-get update
        - tlmgr install index
      after_success:
        - Rscript -e 'covr::codecov()'
      warnings_are_errors: true

    - os: osx
      warnings_are_errors: true
