# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: trusty
latex: false
fortran: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

jobs:
  include:
    - r: oldrel
    - r: release
      after_success:
      - Rscript -e 'covr::codecov()'
      warnings_are_errors: false
    - os: osx
      warnings_are_errors: false

env:
  global:
    - CC=gcc-7
    - CXX=g++-7

matrix:
  fast_finish: true

