os: linux
dist: trusty
language: R
sudo: false
latex: false
fortran: false
warnings_are_errors: false

jobs:
  include:
  - os: osx
  - r: release
    after_success: 
    - Rscript -e 'covr::codecov()'
  - r: release
    env:
      - DEVEL_PACKAGES=true
    r_github_packages:
      - RcppCore/Rcpp


