# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

addons:
  apt:
    packages:
      - libxml2-dev
      - librdf0-dev
      - libv8-dev
      - libjq-dev
      - libdb-dev

r_binary_packages:
  - rmarkdown
  - tinytex
  - knitr

r_github_packages:
  - jimhester/covr

matrix:
  include:
    - r: oldrel
      dist: xenial

    - r: release
      dist: xenial
      after_success:
        - Rscript -e 'covr::codecov()'
      warnings_are_errors: true

    - os: osx
      warnings_are_errors: true
