language: r

cache: 
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

sudo: true

fortran: false

before_install:
  - tlmgr install index

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - librdf0-dev
      - libv8-dev
      - libjq-dev
      - libdb-dev
      - libxml2-dev  

r_binary_packages:
  - rmarkdown
  - tinytex
  - knitr
  - xml2  
  - hunspell

r_github_packages:
  - jimhester/covr

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

matrix:
  include:
    - r: oldrel
      dist: xenial

    - r: release
      dist: xenial
      after_success:
        - Rscript -e 'covr::codecov()'
      warnings_are_errors: true

    - os: osx
      warnings_are_errors: true
