# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# tic documentation to get started: https://ropenscilabs.github.io/tic/
# Usually you shouldn't need to change the first part of the file



# Custom parts:

# Header
language: r
sudo: false
latex: true

#env
env:
  global:
  - MAKEFLAGS="-j 2"
  - BUILD_PKGDOWN=FALSE

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true


addons:
  apt:
    packages:
      - libgs-dev
      - librdf0-dev
      - libv8-dev
      - libxml2-dev

r_github_packages:
  - jimhester/covr
  - r-lib/pkgdown

matrix:
  fast_finish: true
  include:
    - r: 3.4
      warnings_are_errors: false
    - r: oldrel
      warnings_are_errors: false
    - r: release
      env: BUILD_PKGDOWN=TRUE
      # DO NOT CHANGE THE CODE BELOW
      before_install:
        - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
        - R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'
        - R -q -e 'remotes::install_github("ropenscilabs/tic", upgrade = "always"); print(tic::dsl_load()); tic::prepare_all_stages()'
        - R -q -e 'tic::before_install()'
      install: R -q -e 'tic::install()'
      after_install: R -q -e 'tic::after_install()'
      before_script: R -q -e 'tic::before_script()'
      script: R -q -e 'tic::script()'
      after_success: R -q -e 'tic::after_success()'
      after_failure: R -q -e 'tic::after_failure()'
      before_deploy: R -q -e 'tic::before_deploy()'
      deploy:
        provider: script
        script: R -q -e 'tic::deploy()'
        on:
          all_branches: true
      after_deploy: R -q -e 'tic::after_deploy()'
      after_script: R -q -e 'tic::after_script()'
      # DO NOT CHANGE THE CODE ABOVE
      script:
        - R CMD build .
        - R CMD check *.tar.gz --as-cran
      after_success:
        - Rscript -e 'covr::codecov(type = "all")'
      warnings_are_errors: true
    - r: devel
      warnings_are_errors: false
    - os: osx
      r:  release
      warnings_are_errors: true
    - os: osx
      r:  oldrel
      warnings_are_errors: true