language: r

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

sudo: true
fortran: false

addons:
  apt:
    packages:
      - libgs-dev
      - librdf0-dev
      - libv8-dev
      - libxml2-dev

r_github_packages:
  - jimhester/covr
  - r-lib/pkgdown

matrix:
  fast_finish: true
  include:
    - r: 3.4
      warnings_are_errors: false
    - r: oldrel
      warnings_are_errors: false
    - r: release
      script:
        - R CMD build .
        - R CMD check *.tar.gz --as-cran
        - PKG_TARBALL=$(ls -d -1t "$PWD/"*.tar.gz | head -n 1)
        - echo $PKG_TARBALL
      after_success:
        - Rscript -e 'covr::codecov(type = "all")'
        - Rscript -e 'pkgdown::build_site()'
      deploy:
        provider: pages
        skip_cleanup: true
        keep_history: false
        on:
          branch:
            - gh-pages
      warnings_are_errors: true
    - r: devel
      warnings_are_errors: false
    - os: osx
      r:  release
      warnings_are_errors: true
    - os: osx
      r:  oldrel
      warnings_are_errors: true
