os: linux
dist: trusty
language: R
sudo: false
latex: false
fortran: false
warnings_are_errors: false

# Attempt to force more recent c++ compiler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

jobs:
  include:
  - os: osx
  - r: release
    env:
      - CC=gcc-7
      - CXX=g++-7
    after_success: 
    - Rscript -e 'covr::codecov()'
  - r: release
    env:
      - DEVEL_PACKAGES=true
      - CC=gcc-7
      - CXX=g++-7
    r_github_packages:
      - RcppCore/Rcpp


