os: linux
dist: trusty

language: R
sudo: required
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/libgit2/ci-dependencies trusty libgit2deps'
        key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=bintray'
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

env:
  - CC=gcc-7 CXX=g++-7

r_packages:
  - covr

install:
  - sudo apt-get install libboost-dev libboost-regex-dev
  - git clone --depth 1 https://github.com/r-lib/remotes && R CMD build --no-build-vignettes remotes && R CMD INSTALL remotes*tar.gz && rm -rf remotes remotes*tar.gz
  - R -e 'install.packages("curl")' -e 'remotes::install_deps(".", dependencies = TRUE)'

after_success:
  - Rscript -e 'library(covr); codecov()'
