language: r

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

sudo: true
fortran: false

addons:
  apt:
    packages:
      - libgs-dev
      - librdf0-dev
      - libv8-dev
      - libxml2-dev

r_github_packages:
  - jimhester/covr

matrix:
  include:
    - r: 3.4
      warnings_are_errors: false
    - r: oldrel
      warnings_are_errors: false
    - r: release
      script:
        - R CMD check *tar.gz --as-cran
      after_success:
        - Rscript -e 'covr::codecov(type = "all")'
      warnings_are_errors: true
    - r: devel
      warnings_are_errors: false
    - os: osx
      warnings_are_errors: true
