# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
latex: false
fortran: false

r_binary_packages:
  - rmarkdown
  - tinytex
  - knitr
  - xml2
  - hunspell

r_github_packages:
  - jimhester/covr

matrix:
  include:
    - r: oldrel
      dist: xenial

    - r: release
      dist: xenial
      after_success:
        - Rscript -e 'covr::codecov()'
      warnings_are_errors: true

    - os: osx
      warnings_are_errors: true

addons:
  apt:
    packages:
      - librdf0-dev
      - libv8-dev
      - libjq-dev
      - libdb-dev