# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os:
  - linux

language: R
sudo: false
cache: packages

addons:
  apt:
    sources:
     - sourceline: 'deb https://dl.bintray.com/libgit2/ci-dependencies trusty libgit2deps'
       key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=bintray'

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
