# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

apt_packages:
  - libv8-dev

r_binary_packages:
  - xml2
  - rmarkdown
  - tinytex
  - knitr

matrix:
  include:
    - r: oldrel
      dist: xenial

    - r: release
      dist: xenial
      after_success:
        - Rscript -e 'covr::codecov()'
      warnings_are_errors: true

    - os: osx
      warnings_are_errors: true
