# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
latex: false

r_binary_packages:
  - knitr

matrix:
  include:
    - r: oldrel
      dist: xenial
      addons:
        apt:
          packages:
            - libpoppler-cpp-dev
            - libapparmor-dev 

    - r: release
      dist: xenial
      addons:
        apt:
          packages:
            - libpoppler-cpp-dev
            - libapparmor-dev 
      after_success:
        - Rscript -e 'covr::codecov()'
      warnings_are_errors: true

    - os: osx
      warnings_are_errors: true
