# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
dist: trusty
latex: false
fortran: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
  packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.5

r_binary_packages:
  - knitr

# Use gcc 4.9
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

jobs:
  include:
    - r: oldrel
    - r: release
      after_success:
      - Rscript -e 'covr::codecov()'
      warnings_are_errors: true
    - os: osx
      warnings_are_errors: true

matrix:
  fast_finish: true

env:
  global:
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"

