language: r

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

sudo: true
fortran: false

addons:
  apt:
    packages:
      - libgs-dev
      - librdf0-dev
      - libv8-dev
      - libxml2-dev

r_github_packages:
  - jimhester/covr

matrix:
  fast_finish: true
  include:
    - r: 3.4
      warnings_are_errors: false
    - r: oldrel
      warnings_are_errors: false
    - r: release
      script:
        - R CMD check *tar.gz --as-cran
      after_success:
        - Rscript -e 'covr::codecov(type = "all")'
      before_deploy:
        - Rscript -e 'remotes::install_cran("pkgdown")'
        - R CMD INSTALL .
        - Rscript -e 'pkgdown::build_site()'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: "docs"
          keep-history: true
       on:
         branch: gh-pages
      warnings_are_errors: true
    - r: devel
      warnings_are_errors: false
    - os: osx
      r:  release
      warnings_are_errors: true
    - os: osx
      r:  oldrel
      warnings_are_errors: true
