# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: trusty
latex: false
fortran: false


jobs:
  include:
    - r: oldrel
    - r: release
      after_success:
      - Rscript -e 'covr::codecov()'
      warnings_are_errors: false
    - os: osx
      warnings_are_errors: false

matrix:
  fast_finish: true

